3025391 Clean Up UX
Etroid/feeds_migrate pull request #2
Opened 2019-02-11 17:16 UTC by PapaGrande

2019-02-14 19:01 UTC, MegaChriz commented
- When I select an other destination, the vertical tab 'Source' gets focus. Ideally, the destination tab would keep focus.
  `FeedTypeForm::ajaxCallback()` probably has the answer to get that right:

  ```php
  // Set URL hash so that the correct settings tab is open.
  if (isset($form[$type . '_configuration']['#id'])) {
    $hash = ltrim($form[$type . '_configuration']['#id'], '#');
    $response->addCommand(new SetHashCommand($hash));
  }
  ```

  There's already commented out code for this available. See `MigrationForm::ajaxCallback()`.

- ```php
  // Filter out empty and null plugins.
  if (in_array($id, ['null', 'empty'])) {
    continue;
  }
  ```
  I see you hard-coded filtering out plugins 'null' and 'empty'. What are these plugins and why do they need to be filtered out?

- Martin and I think that the visibility of panes can be better handled via AJAX than using `#states` as you used in the following:

  ```php
  // Toggle visibility of fetcher & parser fields depending on source value.
  if (in_array($type, ['fetcher', 'parser'])) {
    $form[$type . '_wrapper']['id']['#states'] =[
      'visible' => [
        'select[name="source"]' => ['value' => 'url']
      ]
    ];
  }
  ```

  So replace above with an AJAX implementation.

  I think the following piece of code demonstrates how Feeds handles that:

  ```php
  if ($this->pluginHasForm($plugin, 'configuration')) {
    $form_builder = $this->formFactory->createInstance($plugin, 'configuration');

    $plugin_form = $form_builder->buildConfigurationForm([], $plugin_state);
    $form[$type . '_configuration'] = [
      '#type' => 'details',
      '#group' => 'plugin_settings',
      '#title' => $this->t('@type settings', ['@type' => ucfirst($type)]),
    ];
    $form[$type . '_configuration'] += $plugin_form;
  }
  ```

  So something conditional makes the form element appear.

2019-02-21 18:44 UTC, MegaChriz commented
```php
// Filter out empty and null migration plugins as those aren't valid feeds
// source or destination.
if (in_array($id, ['null', 'empty'])) {
  continue;
}
```
According to https://www.drupal.org/project/drupal/issues/2857104, it sounds like that the 'null' plugin is a placeholder for a missing Migration plugin.

The D7 version of Feeds had something like that, there it is called "FeedsMissingPlugin". The D7 version of Feeds fixed filtering out this plugin by overriding the method `pluginType()` and returning "missing" there.

I think we can't use the same strategy here, but what we can do is altering the plugin metadata and add something like a key “hidden” to it. The user interface then skips migration plugins which have “hidden” set to true. This avoids having a hard-coded list of plugins to filter out within the UI code.

2019-02-21 18:50 UTC, MegaChriz commented
Perhaps instead of "hidden", “no_ui” would be better for this key, as we already have such one for field types.

2019-02-26 02:28 UTC, irinaz commented
Hi, 
I installed branch [PapaGrande/feeds_migrate](/PapaGrande/feeds_migrate) on a new Drupal 8 site  installed it on  new Drupal 8 site  and I am missing button "add migration" in default migration group http://dev-nicu-database.pantheonsite.io/admin/structure/migrate/manage/default/migrations.   Let me know if I need to provide more details. thanks!!

2019-04-10 21:21 UTC, heddn requested changes

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/FeedsMigrateUiParserSuggestion.php
> +   *
Missing comment text?

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/FeedsMigrateUiParserSuggestion.php
> +   *
Missing comment text?

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/FeedsMigrateUiParserSuggestion.php
> +   *
Missing comment text?

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/FeedsMigrateUiParserSuggestion.php
> +   *
Missing comment text?

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/Form/MigrationMappingForm.php
> +        ]));
whitespace.

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/Form/MigrationMappingFormBase.php
> +          '@destination_field' => $this->migrationEntityHelper()->getMappingFieldLabel($this->key),
Whitespace.

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/Form/MigrationMappingFormBase.php
> +        ]));
Whitespace.

2019-04-10 21:21 UTC, heddn commented on modules/feeds_migrate_ui/src/Form/MigrationMappingFormBase.php
> +   * ----------- .*/
Missing comment text?

2019-04-10 22:20 UTC, closed without merging